"""Q_Diffuser_Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hNBx_OZTusmwAmROHXGquUsfsiYz084

RECALL: Diff models add noise to the data and then train the model to predict the noise, so you can later denoise iteratively. Input: noisy quantized DCT Output: predicted noise/residual


# Hugging Face U-Net (UNet2DModel)
It is the core of the model. It basically is as a “deep multi-scale convolutional neural network with optional attention blocks.”

Key arguments:

| Argument                              | Meaning in your code                                                     |
| ------------------------------------- | ------------------------------------------------------------------------ |
| `sample_size=image_size`              | Input spatial resolution (32×32 grid of 8×8 blocks).                     |
| `in_channels=64`                      | 64 frequency channels → corresponds to 64 DCT coefficients per block.    |
| `out_channels=64`                     | Output is same 64 channels → predicted quantization error per frequency. |
| `layers_per_block=2`                  | Number of ResNet layers per U-Net block.                                 |
| `block_out_channels=(64,128,256,512)` | Width (#filters) per downsampling level.                                 |
| `down_block_types`                    | Which type of downsampling:                                              |

DownBlock2D = regular convolution

AttnDownBlock2D = convolution + attention (captures long-range spatial dependencies). |
| up_block_types | Mirror of downsampling for decoding. Attention helps global consistency. |
| num_class_embeds=101 | Conditional embedding for quality factor (q_label). |

U-Net intuition:

```
# Bu, kod olarak biçimlendirilmiştir
```

 Think encoder-decoder:

Encoder (downsampling):
* Reduces spatial size (32→16→8→4)

* Increases channels (64→128→256→512)

* Extracts multi-scale features


Decoder (upsampling):
* Reconstructs spatial layout

* Combines features via skip connections from encoder

* Produces output of same resolution and channels as input

Attention blocks:
* Help model see global patterns in DCT errors (blocking artifacts span multiple 8×8 blocks)

Parameters in forward pass:
* x: quantized DCT coefficients (B,64,32,32)

* t: diffusion timestep (B,) → controls “noise level” for diffusion model training

* q_label: quality factor class (B,) → tells network which quantization it’s restoring
"""

import torch
import torch.nn as nn
from diffusers import UNet2DModel #pre-built U-Net used by the Hugging Face Diffusers library. You are re-using it instead of writing your own UNet.


# a new PyTorch module DCTRestorationNet that wraps the Hugging Face U-Net and a small normalization layer.
# image_size=32 is the spatial resolution (32×32 grid of 8×8 DCT blocks for a 256×256 image).
class DCTRestorationNet(nn.Module):
    def __init__(self, image_size=32):
        super().__init__()

        # --- 1. The Normalizer ---
        # RAW DCT values are wild:
        # Channel 0 (DC) range: [-1000, +1000]
        # Channel 63 (AC) range: [-5, +5]
        # Neural Networks hate this. They want everything ~ [-1, 1].
        # GroupNorm fixes this automatically without us calculating dataset stats manually.
        # ****MORE DETAIL : GroupNorm(num_groups=1, num_channels=64) with num_groups=1 = LayerNorm across channels (it normalizes each sample across the 64 channels).
        # affine=True means it learns a per-channel scale and bias (so the model can rescale channel 0 down and channel 63 up automatically).
        self.input_normalizer = nn.GroupNorm(num_groups=1, num_channels=64, affine=True)

        # --- 2. The Core U-Net ---
        self.unet = UNet2DModel(
            sample_size=image_size,  # Spatial resolution (32x32 blocks)

            # THE KEY: 64 Channels
            # Standard Stable Diffusion uses 4 channels (Latents).
            # We use 64 channels because we have 64 frequency bands.
            # -->Key change from image U-Nets: instead of 3 RGB channels, your input has 64 frequency channels (one per DCT coefficient per 8×8 block).
            # out_channels=64 — the U-Net outputs a 64-channel tensor (here: predicted quantization error for each frequency).
            in_channels=64,
            out_channels=64,

            # Architecture Depth
            layers_per_block=2,  # How many ResNets per level
            block_out_channels=(64, 128, 256, 512), # Width of the network

            # Downsampling Blocks (Encoding)
            # Which block type to use at each down-sampling stage: "DownBlock2D" = normal conv downsample.
            # "AttnDownBlock2D" = convolution + attention inside the block (helps the model learn long-range/global relationships across the 32×32 grid).
            # Using several attention blocks helps capture global patterns of quantization error.
            down_block_types=(
                "DownBlock2D",      # Standard Conv
                "AttnDownBlock2D",  # Convolution + Attention (Learn global patterns)
                "AttnDownBlock2D",
                "AttnDownBlock2D",
            ),

            # Mirror for the decoder (upsampling). Attention in up blocks again helps global consistency.
            # Upsampling Blocks (Decoding)
            up_block_types=(
                "AttnUpBlock2D",
                "AttnUpBlock2D",
                "AttnUpBlock2D",
                "UpBlock2D",
            ),

            # CONDITIONING: Q-Scale
            # We treat the Q-Scale (1-100) like a "Class Label".
            # The model learns: "If Class=30, the noise looks like X."
            # "If Class=10, the noise looks like Y."
            num_class_embeds=101,
        )

    def forward(self, x, t, q_label):
        """
        x: (Batch, 64, 32, 32) - The Quantized DCT Coefficients
        t: (Batch)             - Diffusion Timestep (0-1000)
        q_label: (Batch)       - The Quality Factor (e.g. 30)
        ****************************************************************************
        x: your input tensor (batch of quantized DCT coefficient maps).
        t: diffusion timestep(s) — diffusion models use timesteps to control noise level.
        q_label: class label per sample (int tensor), tells the U-Net which q_scale to condition on.
        """
        # 1. Normalize the unbalanced DCT inputs
        # Apply the learnable normalization to every input sample. After this, channels are roughly on similar scales (so training focuses on real error patterns, not raw amplitude differences).
        x_norm = self.input_normalizer(x)

        # 2. Predict the noise/error
        # We pass q_label into 'class_labels' to condition the model
        # Call the Hugging Face U-Net: It takes the normalized input x_norm, the diffusion timestep t, and class_labels=q_label.
        # .sample is the actual predicted tensor returned by the UNet model (shape (B,64,32,32)).
        # Important semantic note: what the UNet predicts depends on how you set up training (typical options: predict the added noise epsilon, or predict the denoised x0, or other parametrizations). In many diffusion training setups the model predicts the noise epsilon so loss compares predicted noise vs the true noise added to the target.
        output = self.unet(x_norm, t, class_labels=q_label).sample
        return output


"""# The surrounding pipeline & diffusion logic (explained simply)

1. **Data pipeline** (what you described earlier):

   * Take a regular image → crop to 256×256.
   * Compute blockwise DCT (8×8 blocks → each block produces 64 coefficients).
   * Apply a quantization matrix scaled by `q_scale` to produce *quantized integers* (this is the “bad” compressed representation).
   * Compute the **quantization error** = (original DCT coefficients) − (dequantized quantized coefficients). Your *target* is this error per coefficient (you said in range −0.5..0.5 after normalization; that’s good).
   * Reshape so model sees a 64-channel image with spatial size 32×32 → tensor `(C=64,H=32,W=32)`.

2. **Training with diffusion** (the idea you wrote):

   * Diffusion’s job here: *learn to denoise/predict the quantization error map*.
   * Training steps (high level):

     * Sample a target error map `e` (your true error).
     * Sample noise `ε ∼ N(0, I)`.
     * Choose a timestep `t` and produce `e_t = alpha_t * e + sigma_t * ε` (forward diffusion).
     * Condition the U-Net on the *quantized coefficients* (the degraded input) and on `q_label` and `t`.
     * Model predicts `ε_hat` (or `e_hat`, depending on prediction type).
     * Loss = MSE(ε_hat, ε) if you predict noise; or MSE(e_hat, e) if you predict the clean error directly.

3. **At inference**:

   * You feed the quantized coefficients and `q_label` and run the diffusion sampler (reverse process) to obtain a predicted error map.
   * Add predicted error back to quantized integers → inverse DCT → reconstructed image.

---

# Why GroupNorm helps the DC issue

* DC coefficients (channel 0) can be orders of magnitude larger than high-frequency channels.
* If left unnormalized the network will focus on modeling DC and ignore small AC channels.
* `GroupNorm(num_groups=1)` normalizes across channels per sample and `affine=True` lets the layer *learn* the per-channel rescale and bias. This gives the network a learned per-channel balance without needing to compute dataset-level statistics

# Tiny checklist to run this without surprises

* `q_label = q_label.long().to(device)`
* `t = t.long().to(device)`
* `x = x.float().to(device)`
* Verify `UNet2DModel` returns `.sample` in your diffusers version (some classes return `sample` inside a `ModelOutput`).
* Confirm what the UNet expects for conditioning the quantized coefficients — many diffusers pipelines let you pass `encoder_hidden_states` or `added_cond_kwargs`.

What you need for a training pipeline:

* Dataset & DataLoader → batch your data

* Model → already defined (DCTRestorationNet)

* Optimizer → e.g., Adam

* Loss function → e.g., MSE between predicted residuals and true residuals

* Training loop → forward → compute loss → backward → optimizer step

* Optional scheduler, logging, saving models
"""
