# -*- coding: utf-8 -*-
"""QUANTIZATION_DIFFUSER_data_processer_for_DIV2K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nr604r58IjP_WJokEzrZLsW08f1Ze8y4
"""

import os
import math
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from PIL import Image

# --- 1. JPEG CONSTANTS for quantization ---
JPEG_LUM_QUANT = torch.tensor([
    [16, 11, 10, 16, 24, 40, 51, 61],
    [12, 12, 14, 19, 26, 58, 60, 55],
    [14, 13, 16, 24, 40, 57, 69, 56],
    [14, 17, 22, 29, 51, 87, 80, 62],
    [18, 22, 37, 56, 68, 109, 103, 77],
    [24, 35, 55, 64, 81, 104, 113, 92],
    [49, 64, 78, 87, 103, 121, 120, 101],
    [72, 92, 95, 98, 112, 100, 103, 99]
], dtype=torch.float32)

def get_dct_matrix():
    N = 8
    mat = torch.zeros((N, N))
    for u in range(N):
        for x in range(N):
            norm = math.sqrt(1/N) if u == 0 else math.sqrt(2/N)
            mat[u, x] = norm * math.cos(((2*x + 1) * u * math.pi) / (2*N))
    return mat

DCT_MAT = get_dct_matrix()
DCT_MAT_T = DCT_MAT.t()

# ---------------------------
# Base dataset: loads images from a folder (no hard-coded paths)
# ---------------------------
class DIV2KDataset(Dataset):
    def __init__(self, root_dir):
        self.root_dir = root_dir
        self.image_files = sorted([
            f for f in os.listdir(root_dir)
            if f.lower().endswith(('.png', '.jpg', '.jpeg'))
        ])
        if len(self.image_files) == 0:
            raise RuntimeError(f"No images found in {root_dir}")

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root_dir, self.image_files[idx])
        img = Image.open(img_path).convert("RGB")
        return img, 0  # dummy label for compatibility

# ---------------------------
# DCT Restoration Dataset (your existing class, unchanged logic)
# ---------------------------
class DCTRestorationDataset(Dataset):
    def __init__(self, base_dataset, image_size=256, fixed_quality=10):
        self.base_dataset = base_dataset
        self.image_size = image_size
        self.q_scale = self._get_q_scale(fixed_quality)
        '''
        self.transform = T.Compose([
            T.Resize((image_size, image_size)),
            T.ToTensor(),
        ])
        '''
        # --- NEW AUGMENTATION TRANSFORMS ---
        self.transform = T.Compose([
            T.Resize((image_size, image_size)),
            T.RandomHorizontalFlip(p=0.5),  # 50% chance to flip Left/Right
            T.RandomVerticalFlip(p=0.5),    # 50% chance to flip Up/Down
            T.ToTensor(),
        ])

    def __len__(self):
        return len(self.base_dataset)

    def _get_q_scale(self, quality):
        return float(quality)

    def rgb_to_ycbcr(self, img_tensor):
        r, g, b = img_tensor[0], img_tensor[1], img_tensor[2]
        y = 0.299 * r + 0.587 * g + 0.114 * b
        cb = -0.168736 * r - 0.331264 * g + 0.5 * b + 0.5
        cr = 0.5 * r - 0.418688 * g - 0.081312 * b + 0.5
        return torch.stack([y, cb, cr], dim=0)

    def image_to_patches(self, img_channel):
        patches = img_channel.unfold(0, 8, 8).unfold(1, 8, 8)
        patches = patches.contiguous().view(-1, 8, 8)
        return patches

    def dct_2d_batch(self, patches):
        return torch.matmul(DCT_MAT, torch.matmul(patches, DCT_MAT_T))

    def __getitem__(self, idx):
        img_pil, _ = self.base_dataset[idx]
        img_tensor = self.transform(img_pil)  # (3, H, W)

        # RGB -> YCbCr and Y channel in JPEG centered format
        ycbcr = self.rgb_to_ycbcr(img_tensor)
        y_channel = ycbcr[0] * 255.0 - 128.0

        # Patching, DCT, Quantization
        blocks_flat = self.image_to_patches(y_channel)
        dct_coeffs = self.dct_2d_batch(blocks_flat)

        q_table = JPEG_LUM_QUANT * self.q_scale
        q_table = torch.clamp(q_table, min=1.0)

        dct_quantized = torch.round(dct_coeffs / q_table)

        network_input_raw = dct_quantized * q_table
        true_error = dct_coeffs - network_input_raw
        target_error = true_error / q_table

        blocks_h = self.image_size // 8
        blocks_w = self.image_size // 8

        input_stack = dct_quantized.view(blocks_h, blocks_w, 64)
        target_stack = target_error.view(blocks_h, blocks_w, 64)

        input_stack = input_stack.permute(2, 0, 1)
        target_stack = target_stack.permute(2, 0, 1)

        return {
            "pixel_values": input_stack,
            "labels": target_stack,
            "q_scale": self.q_scale
        }

# ---------------------------
# Small helper to build a DataLoader easily
# ---------------------------
def build_dct_loader(dataset_path, image_size=256, q=10, batch_size=1, shuffle=True, num_workers=4):
    base = DIV2KDataset(dataset_path)
    dct = DCTRestorationDataset(base, image_size=image_size, fixed_quality=q)
    return DataLoader(dct, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers, pin_memory=True)

from google.colab import drive
drive.mount('/content/drive')

dataset_path = '/content/drive/MyDrive/IVC_Project/DIV2K_valid_HR'

loader = build_dct_loader(
    dataset_path,
    image_size=256,
    q=10,
    batch_size=1
)

batch = next(iter(loader))
print(batch["pixel_values"].shape)
print(batch["labels"].shape)
print(batch["q_scale"])

"""| Concept        | Controls                         |
| -------------- | -------------------------------- |
| `batch_size`   | Images per **step**              |
| `len(dataset)` | Images per **epoch**             |
| `#epochs`      | How many times images are reused |

"""